### ISSUE TITLE
(A) изменить логику CurrentColor

### ISSUE THREAD

**Issue by ikit-mita** [vinaris/HomeWork1#1]
CurrentColor должно быть вычисляемым свойством - значение не должно храниться, а должно  каждый раз вычисляться при получении.
[Здесь (в тексте вопроса)](http://stackoverflow.com/questions/2030636/c-sharp-read-only-calculated-properties-should-they-be-methods) можно посмотреть пример вычисляемого свойства.

**Comment by vinaris** [comment]
Изменения внесены!
